In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import bokeh.plotting as bkp
from mpl_toolkits.axes_grid1 import make_axes_locatable
%matplotlib inline

In [2]:
from sklearn.cross_validation import KFold
from sklearn.metrics import accuracy_score
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [59]:
# Read in data

pipeline = pd.read_excel('PipelineMultiClass2.xlsx')

In [60]:
# drop the Win_Lose column, so that all other features can be used as the x values.  There are 38 features

X = pipeline.drop('Multiclass', axis = 1)

In [61]:
# the Win_Lose column is the target column or y value

y = pipeline['Multiclass']

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
rfc = RandomForestClassifier(n_estimators=200)

In [64]:
# Train test split using 33% split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [65]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [66]:
rfc_pred = rfc.predict(X_test)

In [67]:
print(confusion_matrix(y_test,rfc_pred))
print('\n')
print(classification_report(y_test,rfc_pred))

[[ 695  195   74]
 [ 244 1283   56]
 [ 124  153 2014]]


             precision    recall  f1-score   support

          0       0.65      0.72      0.69       964
          1       0.79      0.81      0.80      1583
          2       0.94      0.88      0.91      2291

avg / total       0.83      0.83      0.83      4838



In [102]:
new_df = X_test

In [119]:
new_df["Predicted_Labels"] = rfc_pred

new_df["Original_Labels"] = y_test


new_df.head(12)

C:\Users\aforero\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\aforero\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


BidWin%  Fiscal_Year  AdjEstimatedBase+OptionDuration       Amount  \
10550      0.0         2017                               15         0.00   
4170       0.5         2013                               12     59706.26   
10622      0.0         2014                               15         0.00   
7453       0.5         2016                               48    299409.68   
12106      0.0         2014                               15    537000.00   
7159       0.3         2016                               18         0.00   
12798      0.0         2013                               60  39000000.00   
14515      0.0         2016                               48  20000000.00   
183        0.5         2011                               18    499949.00   
10492      0.0         2014                               60         0.00   
14037      0.0         2016                               30   8000000.00   
7499       0.9         2016                               12         0.00   

       Zero  Less1m  1m_10m  10m_30m  Over30m  EstimatedFee%       ...         \
10550     1       0       0        0        0           0.00       ...          
4170      0       1       0        0        0           0.10       ...          
10622     1       0       0        0        0           0.00       ...          
7453      0       1       0        0        0           0.00       ...          
12106     0       1       0        0        0           0.00       ...          
7159      1       0       0        0        0           0.15       ...          
12798     0       0       0        0        1           0.00       ...          
14515     0       0       0        1        0           0.00       ...          
183       0       1       0        0        0           0.00       ...          
10492     1       0       0        0        0           0.00       ...          
14037     0       0       1        0        0           0.00       ...          
7499      1       0       0        0        0           0.15       ...          

       Days_in_Proposal/PriceQuote  Days_in_Negotiation  Days_in_Review  \
10550                            0                    0               0   
4170                             0                    0               0   
10622                            0                    0               0   
7453                            18                    0              39   
12106                            0                    0               0   
7159                           116                    0               0   
12798                            0                    0               0   
14515                            0                    0               0   
183                              0                    0               0   
10492                            0                    0               0   
14037                            0                    0               0   
7499                            16                    0               1   

       Additional Markets / Multi-area / blank  \
10550                                        0   
4170                                         1   
10622                                        0   
7453                                         0   
12106                                        1   
7159                                         0   
12798                                        0   
14515                                        1   
183                                          1   
10492                                        1   
14037                                        0   
7499                                         0   

       Education & Workforce Development  Energy & Environment  \
10550                                  0                     0   
4170                                   0                     0   
10622                                  0                     0   
7453                                   1                    

In [111]:
# Write dataframe to a csv file with the name my_solution_one.csv

new_df.to_csv("my_solution_one.csv")

In [120]:
rfc_train = rfc.predict(X_train)

In [121]:
rfc_train

array([2, 1, 2, ..., 1, 0, 2], dtype=int64)

In [86]:
from pandas import Series, DataFrame

In [93]:
# Set a DataFrame containing the X_test Amount column, the Y_predictions and the y_test sample:

XAmount = X_test['Amount']

df = DataFrame(XAmount)
df.columns = ['Amount']

df["Y_predictions"] = pd.Series(rfc_pred)

df["Y_original"] = pd.Series(y_test)

# Show
df

Amount  Y_predictions  Y_original
10550         0.00            NaN           2
4170      59706.26            0.0           1
10622         0.00            NaN           2
7453     299409.68            NaN           0
12106    537000.00            NaN           2
7159          0.00            NaN           0
12798  39000000.00            NaN           2
14515  20000000.00            NaN           2
183      499949.00            0.0           0
10492         0.00            NaN           2
14037   8000000.00            NaN           2
7499          0.00            NaN           0
7182      77195.00            NaN           0
6435      59845.00            NaN           1
7672      50000.00            NaN           2
5991      48373.00            NaN           0
13512    500000.00            NaN           2
14190  37500000.00            NaN           2
11488         0.00            NaN           2
7640    5160380.73            NaN           0
3804     169996.00            2.0           1
6588     144953.00            NaN           1
5079      84782.00            NaN           1
2746      28000.00            1.0           1
4718       6438.00            2.0           2
13779    300000.00            NaN           2
13148    200000.00            NaN           2
8155    7980977.88            NaN           1
10144    400000.00            NaN           2
5934     350168.00            NaN           0
...            ...            ...         ...
3654      73000.00            0.0           1
1486   32842730.00            1.0           0
9197          0.00            NaN           2
11859         0.00            NaN           2
9692     300000.00            NaN           2
4122     771469.00            2.0           1
9156          0.00            NaN           2
5507      94981.00            NaN           1
11010         0.00            NaN           2
11392         0.00            NaN           2
4736     650000.00            1.0           2
3679          0.00            2.0           1
9362          0.00            NaN           2
9546          0.00            NaN           2
603      344355.00            1.0           2
7687    1350000.00            NaN           2
2033     700000.00            2.0           2
9181          0.00            NaN           2
10891         0.00            NaN           2
262       60937.00            0.0           0
7826      50000.00            NaN           2
765      500000.00            2.0           2
5564      22657.00            NaN           1
10305    120000.00            NaN           2
7675    1000000.00            NaN           2
7207          0.00            NaN           0
12758    500000.00            NaN           2
10260         1.00            NaN           2
11014         0.00            NaN           2
9864          0.00            NaN           2

[4838 rows x 3 columns]

# Logistic Regression:

In [70]:
logmodel = LogisticRegression()

In [74]:
logmodel.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [72]:
predictions = logmodel.predict(X_test)

In [76]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[ 142   26  796]
 [  83   31 1469]
 [  53   37 2201]]


             precision    recall  f1-score   support

          0       0.51      0.15      0.23       964
          1       0.33      0.02      0.04      1583
          2       0.49      0.96      0.65      2291

avg / total       0.44      0.49      0.37      4838



In [97]:
print(predictions[0:1000])

[2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 0 2 2 2 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2
 0 2 2 2 2 2 0 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 0 0 2 2 2 2 2 2 2 0 2 2 2 2 0 2 0 2 0 2 2
 2 2 2 2 2 2 2 2 2 1 2 2 2 0 2 2 2 2 2 2 2 1 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 0 2
 2 2 2 2 2 2 2 2 1 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2
 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2
 2 2 2 2 2 2 2 2 2 0 2 2 